version: '3.8'

services:
  frontend:
    build: ./front-end
    ports:
      - "3001:3001"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - PORT=3001

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    volumes:
      - ./gateway:/app
      - ./shared:/app/shared
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app
    depends_on:
      - redis

  icon-service:
    build: ./icon-service
    ports:
      - "8001:8001"
    volumes:
      - ./icon-service:/app
      - ./shared:/app/shared
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app

  splash-service:
    build: ./splash-service
    ports:
      - "8002:8002"
    volumes:
      - ./splash-service:/app
      - ./shared:/app/shared
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

