version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:8000

  icon-service:
    build: ./icon-service
    volumes:
      - ./icon-service:/app
      - microdawgs_model_cache:/app/shared/cache
      - microdawgs_model_storage:/app/shared/models
      - /app/node_modules
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - HF_HOME=/app/shared/cache
      - TRANSFORMERS_CACHE=/app/shared/cache/transformers
      - DIFFUSERS_CACHE=/app/shared/cache/diffusers
    ports:
      - "8000:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/src
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  microdawgs_model_cache:
    name: microdawgs_model_cache
  microdawgs_model_storage:
    name: microdawgs_model_storage

networks:
  app-network:
    driver: bridge

