version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  icon-service:
    build:
      context: ./icon-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./icon-service:/app
      - /app/models
    environment:
      - MODEL_PATH=/app/models
      - TRANSFORMERS_CACHE=/app/models/cache
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  model-data:
    driver: local

networks:
  app-network:
    driver: bridge

